import NextTopLoader from "nextjs-toploader";
import "bootstrap/dist/css/bootstrap.css";
import "@/assets/css/main.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@/assets/css/animate.min.css";
import "react-loading-skeleton/dist/skeleton.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <NextTopLoader />
      </body>
    </html>
  );
}
